#pragma once
#define ADDRESS_ROM_BANK0_START 0x0000
#define ADDRESS_ROM_BANK0_END	0x3FFF
#define ADDRESS_ROM_BANK1_START 0x4000
#define ADDRESS_ROM_BANK1_END	0x7FFF
#define ADDRESS_VRAM_START		0x8000
#define ADDRESS_VRAM_END		0x9FFF
#define ADDRESS_SRAM_START		0xA000
#define ADDRESS_SRAM_END		0xBFFF
#define ADDRESS_WRAM_START		0xC000
#define ADDRESS_WRAM_END		0xDFFF
#define ADDRESS_ECHO_START		0xE000
#define ADDRESS_ECHO_END		0xFDFF
#define ADDRESS_OAM_START		0xFE00
#define ADDRESS_OAM_END			0xFE9F
#define ADDRESS_IO_START		0xFF00
#define ADDRESS_IO_END			0xFF7F
#define ADDRESS_HRAM_START		0xFF80
#define ADDRESS_HRAM_END		0xFFFE

// Sizes
#define ROM_BANK0_SIZE (ADDRESS_ROM_BANK0_END - ADDRESS_ROM_BANK0_START + 1)
#define ROM_BANK1_SIZE (ADDRESS_ROM_BANK1_END - ADDRESS_ROM_BANK1_START + 1)
#define VRAM_SIZE (ADDRESS_VRAM_END - ADDRESS_VRAM_START + 1)
#define SRAM_SIZE (ADDRESS_SRAM_END - ADDRESS_SRAM_START + 1)
#define WRAM_SIZE (ADDRESS_WRAM_END - ADDRESS_WRAM_START + 1)
#define ECHO_SIZE (ADDRESS_ECHO_END - ADDRESS_ECHO_START + 1)
#define OAM_SIZE (ADDRESS_OAM_END - ADDRESS_OAM_START + 1)
#define IO_SIZE (ADDRESS_IO_END - ADDRESS_IO_START + 1)
#define HRAM_SIZE (ADDRESS_HRAM_END - ADDRESS_HRAM_START + 1)
